using PhantomRevealer
using LaTeXStrings
using CairoMakie
"""
Generate the image from the dump files generated by `Slicing_disk.jl`
    by Wei-Shan Su,
    Febuary 28, 2024
"""

function Constructing_figure(filepath::String)
    @info "-------------------------------------------------------"
    # ------------------------------PARAMETER SETTING------------------------------
    # Figure setting
    Figure_format :: String = "pdf"
    figsize :: Tuple = (8,8)
    dpi = 450
    slabel = latexstring(L"$r$ [au]")
    zlabel = latexstring(L"$z$ [au]")
    colormap_rho :: String = "RdYlGn"
    colormap_v :: String = "RdBu"
    colormap_vorticity :: String = "RdBu"
    clim_rho :: Vector = [7.1e-18,1e-14]
    clim_vs :: Vector = [-1.5e+5,1.5e+5]
    clim_vz :: Vector = [-1.5e+5,1.5e+5]
    clim_vorticity :: Vector = [-25.5,25.5]
    Slice_ϕ :: Union{Nothing,Float64} = 0                                             # The azimuthal angle of vertical structure (in degree). Taking azimuthally averaging if `nothing`.
    # -----------------------------------------------------------------------------
    # Packaging parameters
    filename = splitext(filepath)[1]
    File_prefix = split(filename, "_")[1]
    number_data = extract_number(filename)

    # Verifing data
    Result :: Analysis_result = Read_HDF5(filepath)
    if Result.params["Analysis_type"] != "Slicing_disk"
        error("InputError: The Analysis type of data needs to be `Slicing_disk`!")
    end

    # Modified Colormap to have white color at the bottom
    colormap_rho_modified = colormap_with_base(colormap_rho)

    # Packaging parameters
    clims = [clim_rho, clim_vs,clim_vz, clim_vorticity]

    transfer_cgs!(Result)

    # Finding column_index
    target_columns :: Vector{String} = ["rho_g","rho_d","vs_g","vs_d","vz_g","vz_d","∇×vϕ_g","∇×vϕ_d"]
    target_column_index :: Vector{Int64} = zeros(Int64, length(target_columns))
    for key in keys(Result.column_names)
        value = strip(Result.column_names[key])  
        actual_name = strip(split(value)[end], ['[', ']'])  
        for (i, target) in enumerate(target_columns)
            if actual_name == target 
                target_column_index[i] = key
            end
        end
    end

    # Setup plotting target
    timestamp = Result.time
    s = Result.axes[1]
    ϕ = Result.axes[2]
    z = Result.axes[3]
    rho_label = L"$\rho$ [g\ cm$^{-3}$]"
    vs_label = L"$v_r$ [cm\ s$^{-1}$]"
    vz_label = L"$v_z$ [cm\ s$^{-1}$]"
    Vorticity_label = L"Vorticity [$10^{-10}$ s$^{-1}$]"

    # Determining the azimuthal angle
    if !(isnothing(Slice_ϕ))
        Slice_ϕ_index = value2closestvalueindex(ϕ,Slice_ϕ*(π/180))
        Slice_ϕ_real = ϕ[Slice_ϕ_index]*(180/π)
        anatonate_label = latexstring(L"$t = ",Int64(round(timestamp)), L"$ yr, $\phi$ = ", Int64(round(Slice_ϕ_real)),L"^{\circ}")
    else
        anatonate_label = latexstring(L"$t = ",Int64(round(timestamp)), L"$ yr")
    end
    
    reduced_array = Vector{Array{Float64}}(undef, length(target_columns))
    for (i,index) in enumerate(target_column_index)
        if isnothing(Slice_ϕ)
            reduced_array[i] = grid_reduction(Result.data_dict[index],2)
        else
            reduced_array[i] = Result.data_dict[index][:,Slice_ϕ_index,:]
        end
    end

    rhog, rhod, vsg, vsd, vzg, vzd, curlvϕg, curlvϕd = reduced_array
    threadshold = 1.15*clims[1][1]
    vsg[rhog .< threadshold] .= NaN
    vsd[rhod .< threadshold] .= NaN
    vzg[rhog .< threadshold] .= NaN
    vzd[rhod .< threadshold] .= NaN
    curlvϕg[rhog .< threadshold] .= NaN
    curlvϕd[rhod .< threadshold] .= NaN


    # Preparing plotting backend
    activate_backend("Cairo")
    Fax = FigureAxes(4,2,figsize=figsize,sharex=true, sharey=true)
    heatmap!(Fax.axes[1,1],s ,z ,rhog ,colormap=colormap_rho_modified, colorrange=clim_rho, colorscale=log10)
    set_annotation!(Fax,(1,1),latexstring(anatonate_label," (Gas)"))
    heatmap!(Fax.axes[1,2],s ,z ,rhod ,colormap=colormap_rho_modified, colorrange=clim_rho, colorscale=log10)
    set_annotation!(Fax,(1,2),latexstring(anatonate_label," (Dust)"))
    set_colorbar!(Fax,(1,1),clabel=rho_label,link_row_colormap=true)

    heatmap!(Fax.axes[2,1],s ,z ,vsg ,colormap= colormap_v, colorrange=clim_vs, colorscale=Symlog10Scale(clim_vs...))
    set_annotation!(Fax,(2,1),latexstring(anatonate_label," (Gas)"))
    heatmap!(Fax.axes[2,2],s ,z ,vsd ,colormap= colormap_v, colorrange=clim_vs, colorscale=Symlog10Scale(clim_vs...))
    set_annotation!(Fax,(2,2),latexstring(anatonate_label," (Dust)"))
    set_colorbar!(Fax,(2,1),clabel=vs_label,link_row_colormap=true)

    heatmap!(Fax.axes[3,1],s ,z ,vzg ,colormap= colormap_v, colorrange=clim_vz, colorscale=Symlog10Scale(clim_vz...))
    set_annotation!(Fax,(3,1),latexstring(anatonate_label," (Gas)"))
    heatmap!(Fax.axes[3,2],s ,z ,vzd ,colormap= colormap_v, colorrange=clim_vz, colorscale=Symlog10Scale(clim_vz...))
    set_annotation!(Fax,(3,2),latexstring(anatonate_label," (Dust)"))
    set_colorbar!(Fax,(3,1),clabel=vz_label,link_row_colormap=true)

    heatmap!(Fax.axes[4,1],s ,z ,-curlvϕg*1e10 ,colormap= colormap_vorticity, colorrange=clim_vorticity, colorscale=identity)
    set_annotation!(Fax,(4,1),latexstring(anatonate_label," (Gas)"))
    heatmap!(Fax.axes[4,2],s ,z ,-curlvϕd*1e10 ,colormap= colormap_vorticity, colorrange=clim_vorticity, colorscale=identity)
    set_annotation!(Fax,(4,2),latexstring(anatonate_label," (Dust)"))
    set_colorbar!(Fax,(4,1),clabel=Vorticity_label,link_row_colormap=true)

    set_xlabel!(Fax,slabel)
    set_ylabel!(Fax,zlabel)

    if isnothing(Slice_ϕ)
        output_filename = "$(File_prefix)_$(number_data)_aziavegTTTlog.$(Figure_format)"
    else
        output_filename = "$(File_prefix)_$(number_data)_$(Slice_ϕ)degTTTlog.$(Figure_format)"
    end
    save_Fig!(Fax, output_filename, dpi)
    close_Fig!(Fax)
end

function main()
    # Commendline variable setting
    if length(ARGS) < 1
        println("Usage: julia Slicing_disk_fig.jl <filename>")
        exit(1)
    end

    files = ARGS             

    First_logging()

    for file in files
        @info "File: $file"
        @time_and_print begin
            Constructing_figure(file)
        end 
    end

    @info "\nEnd analysis!"
end

main()